name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Commisery
      uses: KevinDeJong-TomTom/commisery-action@v0.1.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull_request: ${{ github.event.number }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install .

    - name: Test with pytest
      run: |
        pytest --cov=. --cov-report=xml
